module.exports = {
  DEBUG: process.env.NODE_ENV === 'development',

  siteName: 'Packrs',
  author: 'vipin',
  description: 'A delivery platform for anything',
  siteUrl: 'https://www.packrs.co/',
  image: 'https://packrs.co/images/packrs-poster.png',
  graphqlUri: 'https://packrs-api.now.sh/graphql',
  twitterUrl: 'https://twitter.com/PackrsOfficial',
  fbUrl: 'https://www.facebook.com/PackrsOfficial',
  instagramUrl: 'https://www.instagram.com/packrs_official',
  mediumPublicationUrl: 'https://medium.com/packrs',
  twitter: '',
  fbUserId: '@NAME-HERE',
  fbAppID: '@NAME-HERE',
  type: 'website',
  googleAnalytics: 'UA-1390187-42',
  mailchimpUrl:
    'https://appfuel.us12.list-manage.com/subscribe/post?u=b54c5e68fbc05aab49770e457&amp;id=3b79b094e9',
  backgroundColor: '#e0e0e0',
  themeColor: '#33b760',
  businessCategories: [
    { name: 'Beauty', value: 'beauty' },
    { name: 'Books', value: 'books' },
    { name: 'Clothing & Accessories', value: 'clothingAndAccessories' },
    { name: 'Electronics (Accessories)', value: 'electronicsAccessories' },
    { name: 'Fashion Jewelry', value: 'fashionJewelry' },
    { name: 'Food and Beverage', value: 'foodAndBeverage' },
    { name: 'Grocery & Gourmet Food', value: 'groceryGourmetFood' },
    { name: 'Handmade', value: 'handmade' },
    { name: 'Health & Personal Care', value: 'healthPersonalCare' },
    { name: 'Home & Garden', value: 'homeAndGarden' },
    { name: 'Industrial & Scientific', value: 'industrialAndScientific' },
    { name: 'Luggage & Travel Accessories', value: 'luggageAccessories' },
    { name: 'Mobiles, Mobile Accessories', value: 'mobilesAccessories' },
    { name: 'Music', value: 'music' },
    { name: 'Musical Instruments', value: 'musicalInstruments' },
    { name: 'Office Products', value: 'officeProducts' },
    { name: 'Outdoors', value: 'outdoors' },
    { name: 'Personal Computers', value: 'personalComputers' },
    { name: 'Pharmaceuticals', value: 'pharmaceuticals' },
    { name: 'Professional Services', value: 'professionalServices' },
    { name: 'Shoes, Handbags & Sunglasses', value: 'shoesHandbagsSunglasses' },
    { name: 'Shops', value: 'shops' },
    { name: 'Software & Computer Games', value: 'softwareComputerGames' },
    { name: 'Tools & Home Improvement', value: 'toolsHomeImprovement' },
    { name: 'Toys & Games', value: 'toysGames' },
    { name: 'Video, DVD & Blu-Ray', value: 'videoBluRay' },
    { name: 'Watches', value: 'watches' },
  ],
};
